## NUMPY 

* array processing package
* provides high performance multi dimensional array object
* and tools for woking with them
* scientific computing
* bindings of c++ lib -- quick operations
* 

In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4,5]
arr=np.array(lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
print(arr)

[1 2 3 4 5]


In [ ]:
arr.shape ## says no of row and function

In [6]:
arr

array([1, 2, 3, 4, 5])

In [9]:
l1=[1,2,3,4,5]
l2=[1,2,3,5,6,]
l3=[2,4,6,6,7]
a1=np.array([l1,l2,l3])


In [10]:
a1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 5, 6],
       [2, 4, 6, 6, 7]])

In [11]:
a1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 5],
       [6, 2, 4],
       [6, 6, 7]])

In [12]:
a1.reshape(2,3)

ValueError: cannot reshape array of size 15 into shape (2,3)

In [13]:
a1.shape

(3, 5)

In [15]:
arr.reshape(5,1)  ## giving 2d array

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
a1.reshape(1,15)

array([[1, 2, 3, 4, 5, 1, 2, 3, 5, 6, 2, 4, 6, 6, 7]])

* indexing

In [18]:
a1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 5, 6],
       [2, 4, 6, 6, 7]])

In [19]:
a1[1,2]

3

In [20]:
arr[2]

3

In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
a1[0:2, 0:2]

array([[1, 2],
       [1, 2]])

In [24]:
a1[:,3:]

array([[4, 5],
       [5, 6],
       [6, 7]])

In [27]:
a1[1:,3:]

array([[5, 6],
       [6, 7]])

In [34]:
a2=np.arange(0,10)

In [35]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a1=np.array([l1,l2,l3])

In [39]:
a1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 5, 6],
       [2, 4, 6, 6, 7]])

In [46]:
a3=np.arange(0,15,step=3)

In [45]:
a3

array([ 0,  3,  6,  9, 12])

In [47]:
np.linspace(1,10,55) ## to get 55 equi spaced points between intervals

array([ 1.        ,  1.16666667,  1.33333333,  1.5       ,  1.66666667,
        1.83333333,  2.        ,  2.16666667,  2.33333333,  2.5       ,
        2.66666667,  2.83333333,  3.        ,  3.16666667,  3.33333333,
        3.5       ,  3.66666667,  3.83333333,  4.        ,  4.16666667,
        4.33333333,  4.5       ,  4.66666667,  4.83333333,  5.        ,
        5.16666667,  5.33333333,  5.5       ,  5.66666667,  5.83333333,
        6.        ,  6.16666667,  6.33333333,  6.5       ,  6.66666667,
        6.83333333,  7.        ,  7.16666667,  7.33333333,  7.5       ,
        7.66666667,  7.83333333,  8.        ,  8.16666667,  8.33333333,
        8.5       ,  8.66666667,  8.83333333,  9.        ,  9.16666667,
        9.33333333,  9.5       ,  9.66666667,  9.83333333, 10.        ])

In [49]:
a1[1,3]=99

In [50]:
a1

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3, 99,  6],
       [ 2,  4,  6,  6,  7]])

* copy and broadcasting

In [51]:
a2[3:]=100

In [52]:
a2

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

* refernce type -- multiple variable name store same data -- mutables -- list , set , dict
* value type -- each variable name has its own copy of data -- immutables -- tuple, string , int , char
* hence in value type changing in 1 variable does not affect the other , 
* but in reference type change in  1 results in change in all variable name object-- bcz inka object toh 1 hi h na 


In [53]:
arr1=a2.copy()

In [54]:
a2[3:]=500

In [55]:
a2

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [56]:
arr1

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

## some conditions useful in EDA

In [57]:
val=2
a1<2   ## only ele less than 2 are true

array([[ True, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [59]:
a4=np.arange(0,40,2).reshape(4,5)

In [60]:
a4


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [61]:
a5=np.linspace(40,60,20).reshape(4,5)

In [62]:
a5

array([[40.        , 41.05263158, 42.10526316, 43.15789474, 44.21052632],
       [45.26315789, 46.31578947, 47.36842105, 48.42105263, 49.47368421],
       [50.52631579, 51.57894737, 52.63157895, 53.68421053, 54.73684211],
       [55.78947368, 56.84210526, 57.89473684, 58.94736842, 60.        ]])

In [63]:
a4*a5

array([[   0.        ,   82.10526316,  168.42105263,  258.94736842,
         353.68421053],
       [ 452.63157895,  555.78947368,  663.15789474,  774.73684211,
         890.52631579],
       [1010.52631579, 1134.73684211, 1263.15789474, 1395.78947368,
        1532.63157895],
       [1673.68421053, 1818.94736842, 1968.42105263, 2122.10526316,
        2280.        ]])

In [64]:
a4-a5

array([[-40.        , -39.05263158, -38.10526316, -37.15789474,
        -36.21052632],
       [-35.26315789, -34.31578947, -33.36842105, -32.42105263,
        -31.47368421],
       [-30.52631579, -29.57894737, -28.63157895, -27.68421053,
        -26.73684211],
       [-25.78947368, -24.84210526, -23.89473684, -22.94736842,
        -22.        ]])

In [65]:
a6=np.ones(4)

In [66]:
a6

array([1., 1., 1., 1.])

In [68]:
a7=np.ones((2,5),dtype=int)

In [69]:
a7

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [70]:
a8=np.random.rand(3,6)

In [71]:
a8

array([[0.60083421, 0.85089187, 0.92824035, 0.04703226, 0.8480573 ,
        0.71713876],
       [0.46283236, 0.8951079 , 0.25008635, 0.84091716, 0.34614044,
        0.34091625],
       [0.86360296, 0.72730252, 0.66232177, 0.42068434, 0.25271254,
        0.47056263]])

In [72]:
a9=np.random.randn(4,4)  ## random values based on standard normal distribution

In [73]:
a9

array([[ 0.26083085,  0.0962473 ,  0.21633852,  0.82054799],
       [-0.27529431,  1.22426637, -0.28425447, -0.57306466],
       [-0.41641815, -1.11829027,  2.64889682,  0.26602785],
       [-1.86972835, -1.54104748, -0.08549323, -1.58415999]])